### ISSUE TITLE
DigitalOcean Community Code of Conduct

### ISSUE THREAD

**Issue by kev-odin** [do-community/cloud_haiku#2422]
Hello @MattIPv4 and @hazel-nut 

I wanted to thank you hosting Hacktoberfest 2022! I have always wanted to contribute more to open-source and this year I finally decided to jump into the deep end :)

I noticed that our community does not have a Code of Conduct markdown file. I propose that we should make the reference easier to find [DigitalOcean Code of Conduct](https://www.digitalocean.com/community/pages/code-of-conduct). This may be shown as a badge in the repository or a link in the `readme.md`.

![image](https://user-images.githubusercontent.com/60195141/195436914-7cc48b09-e794-490d-950d-992e5cf66977.png)

compared with [vscode-pets](https://github.com/tonybaloney/vscode-pets):

![image](https://user-images.githubusercontent.com/60195141/195437789-9f6fd338-6967-42d7-aaf1-2f5aedfd64d4.png)

Any feedback or thoughts? 

Cheers!
Kevin

**Comment by MattIPv4** [comment]
I would defer to @ltagliaferri as she leads maintaining this repo :)

**Comment by 2022H1030042G** [comment]
Hi @kev-odin @ltagliaferri , I would like to work on it. Let me know if it can be assigned to me.
