### ISSUE TITLE
New Pull Requests failing

### ISSUE THREAD

**Issue by lilibethocando** [do-community/cloud_haiku#2567]
Hello, it appears that all new PR for adding haikus are failing after "Actions" is run due to old PRs that failed before for different users. 
Could you please validate it? 
For instance, none of the 8 failures below is my user, however, my PR test failed:

"Run npm test
> cloud_haiku@1.0.0 test
> tap test.js -R min --no-coverage-report --timeout=300
  8320 passing 
 8320 passing (56s)
  8 failing
Error: Process completed with exit code 1."

**Comment by NewMeem22** [comment]
i can do this

**Comment by ltagliaferri** [comment]
Yeah, you can still open a PR, it is just that the test is not running each time and the syllable validator is not perfect. I am doing intermittent fixing
