### ISSUE TITLE
New Pull Requests failing

### ISSUE THREAD

**Issue by staiton** [do-community/cloud_haiku#2584]
A lot of people are having trouble to submit a new pull request

![image](https://user-images.githubusercontent.com/55883166/196703047-6e2c528c-c4bc-4b8e-b01f-eaae85a29cca.png)

![image](https://user-images.githubusercontent.com/55883166/196703207-ff351a13-e5c4-4484-ae81-fccf5c22e1bf.png)

**Comment by ltagliaferri** [comment]
You can still open a PR, it is just that the test is not running each time and the syllable validator is not perfect. I am doing intermittent fixing

**Comment by staiton** [comment]
Thank you!
