### ISSUE TITLE
Tests fail when submitted haiku

### ISSUE THREAD

**Issue by goobric** [do-community/cloud_haiku#2930]
goobric silent coder #2929 
I have submitted a haiku within the _haikus directory
These were the steps:
- starred repo
- forked repo
- cloned repo from my github account to my computer
- created a new branch 'myhaiku'
- added a new file to the _haikus directory
- created haiku and saved file
- git add, git commit, git push
- on my forked repo clicked Create Pull Request
- received no conflicts
- yet tests didn't pass!
See attached screen images.
Can you please explain why this happened?
Do I have to submit my haiku again?
Thank you
![231012_haiku_err1](https://github.com/do-community/cloud_haiku/assets/23141638/8128c4a5-b66a-4936-9585-35a5f246da37)
![231012_haiku_err2](https://github.com/do-community/cloud_haiku/assets/23141638/2621ff9a-815f-4018-aa2c-c88f8713104e)

**Comment by Kent-Coleman** [comment]
Following. This also happened to me.

**Comment by CKCarr** [comment]
following. Same issue, did I miss a step?

**Comment by ltagliaferri** [comment]
This is a known issue that has been documented in a number of previous issues. It's not a priority to fix the GH Action right now and will not impact the PR review process.
