### ISSUE TITLE
Syllable Counter

### ISSUE THREAD

**Issue by Darren01** [do-community/cloud_haiku#455]
Your syllable counter can't cope with diacritics ... noösphere has 3 syllables but is counted as having 2 ... can you fix it, please?

**Comment by ltagliaferri** [comment]
The syllable counter is not perfect unfortunately, so we have humans reviewing PRs too and overriding as needed. @beardicus any thoughts about this?

**Comment by beardicus** [comment]
We use the [syllable](https://github.com/words/syllable/) library for these tests. It is english- and ascii-focused and even then it fails occasionally. It's still useful for us as a way to triage pull requests, and we're happy to manually review any false-negatives.
