### ISSUE TITLE
Translating Readme.md

### ISSUE THREAD

**Issue by mRuggi** [do-community/cloud_haiku#917]
I've committed my first haiku ever today and got interested in this kind of poetry.
Would it be useful if i translate the Readme in my mother language? (Italian)
Let me know

**Comment by ltagliaferri** [comment]
Assolutamente, grazie mille per l'offerta

**Comment by mRuggi** [comment]
I submitted a pull request #921

**Comment by ltagliaferri** [comment]
Thank you, we'll review soon!

**Comment by ltagliaferri** [comment]
Thank you @mRuggi 🎉
